### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by theamnesic** [sylvainjule/kirby-autofocus#10]
Hi!

When I upload a new image, i've got a 500 with Kirby 3.6.2: 

![Capture d’écran 2022-02-21 à 13 17 29](https://user-images.githubusercontent.com/242203/154954847-7544c98a-798a-46fc-8c09-345c1ad3a7e6.png)

Any idea how to debug this? 

Thanks!

**Comment by sylvainjule** [comment]
I could reproduce with a file section located at the panel root / site instead of a subpage. It's fixed in latest release, please don't hesitate to reopen if it occured elsewhere for you.
