### ISSUE TITLE
Autofocus not working

### ISSUE THREAD

**Issue by dwd0tcom** [sylvainjule/kirby-autofocus#8]
When I upload a new image the content file for the image still says `Focus: {"x":0.5,"y":0.5}`

**Comment by sylvainjule** [comment]
Are you uploading (not replacing) the files with a Files section?

Do you have anything logged in the console?

**Comment by dwd0tcom** [comment]
I created a new page with no files and tried to upload it directly. 
Which console do you mean?

**Comment by sylvainjule** [comment]
In your browser devtools (Cmd + alt + J on Chrome), on the panel page after and upload?

Could you remove any sensitive / private information from your installation and forward me a zip? This plugin is a bit experimental it's kind of hard to debug without diving right into it.

**Comment by dwd0tcom** [comment]
Ah, I already checked the console. There is no error tho. 

The site is pretty huge, which folders do you exactly need?

**Comment by sylvainjule** [comment]
Only `site` + the name of the kirby version you are using.

Before anything: are you sure the plugin in compiled / loaded? Can you try deleting the `.index.js` in the `media/plugins` folder to force Kirby to create a new one?

**Comment by dwd0tcom** [comment]
I deleted the index.js file but it's still not working. I'll email you the site folder!

**Comment by sylvainjule** [comment]
I have given it a shot. The issue happened when the file section was empty: autofocus wasn't saved for the first image, image 2+ worked.

Latest commit should fix it, please give it a shot and let me know.

**Comment by dwd0tcom** [comment]
Now we're talking! It's working 🥳
Thanks for you help!
